spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: {DB_USER_NAME}
    password: {DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
mf:
  input-file-location: /home/praveen/MutualFundsOut.csv