spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: lenovo123
    driver-class-name: org.postgresql.Driver

mf:
  input-file-location: /home/praveen/MutualFundsOut.csv